name: validate
on:
  push:
    branches:
      - 'main'
      - 'next2'
  pull_request:
    branches:
      - 'main'
      - 'next2'
jobs:
  setup:
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ▶️ Run setup script
        run: npm run setup
